// /// Flutter icons AppIcons
// /// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  AppIcons
// ///      fonts:
// ///       - asset: fonts/AppIcons.ttf
// ///
// /// 
// ///
// import 'package:flutter/widgets.dart';

// class AppIcons {
//   AppIcons._();

//   static const _kFontFam = 'AppIcons';
//   static const String? _kFontPkg = null;

//   static const IconData scan = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData nfc = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData left = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData qr_code = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData x = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData moon = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData settings = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData globe = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData help = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData info = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
